Vagrant.configure(2) do |config|
    config.vm.box = "centos/8"
    config.vm.box_url = "centos/8"

    config.vm.define "lsoulimaS" do |control|
        control.vm.hostname = "lsoulimaS"
        control.vm.network "private_network", ip: "192.168.42.110"
        control.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--cpus", "1"]
            v.customize ["modifyvm", :id, "--memory", "1024"]
            v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]    #boost on networking performance
            v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]           #boost on networking performance
            v.customize ["modifyvm", :id, "--name", "p1-lsoulimaS"]
        end
        # control.vm.provision "shell", path: "setup_server.sh"
    end
end
  